OPENAI_API_KEY =  "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"
ACTIVELOOP_TOKEN = "eyJhbGciOiJIUzUxMiIsImlhdCI6MTY5MDIyMDA1NSwiZXhwIjoxNjkwODI0ODM5fQ.eyJpZCI6ImpiZWFzdG1hbiJ9.AmMWPDqYBtHy_wBvj7WjfiX-iBGv4BPiJDVLZBhDEWLrQX3L4NkSRJebgVDm-JsIDevLBTa7N9hFc4yGfFOmvA"
ACTIVELOOP_ORG_NAME = "69-69"
PIAZZA_EMAIL = "john.eastman@tufts.edu"
PIAZZA_PASSWORD = "Dana#113"