OPENAI_API_KEY =  "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"
ACTIVELOOP_TOKEN = "eyJhbGciOiJIUzUxMiIsImlhdCI6MTY5MDIyMDA1NSwiZXhwIjoxNjkwODI0ODM5fQ.eyJpZCI6ImpiZWFzdG1hbiJ9.AmMWPDqYBtHy_wBvj7WjfiX-iBGv4BPiJDVLZBhDEWLrQX3L4NkSRJebgVDm-JsIDevLBTa7N9hFc4yGfFOmvA"
ACTIVELOOP_ORG_NAME = "69-69"
PIAZZA_EMAIL = "john.eastman@tufts.edu"
PIAZZA_PASSWORD = "Dana#113"